const state={data:null,mode:'uhc',query:''};
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tierValue=t=>{const m=String(t||'').match(/^(HT|LT)([1-5])$/);return m?(m[1]==='HT'?Number(m[2]):10+Number(m[2])):99};
const tierClass=t=>String(t||'').toLowerCase();
const skin=n=>`https://mc-heads.net/avatar/${encodeURIComponent(n)}/64`;
const flag=r=>({EU:'🇪🇺',NA:'🇺🇸',AS:'🇯🇵',OC:'🇦🇺',SA:'🇧🇷',AF:'🇿🇦'})[r]||'🌐';
async function load(){state.data=await fetch('/api/data').then(r=>r.json()); applySettings(); render();}
function applySettings(){const s=state.data.settings||{};$('#serverIp').textContent=s.serverIp||'mc.stabletiers.de';$('#discordLink').href=s.serverDiscord||'#';document.title=(s.siteName||'STABLETIERS')+' — Minecraft PvP Rankings';}
function render(){renderModes();renderSideModes();renderTierlist();renderTop3();renderChanges();renderRegions();}
function filteredPlayers(){const q=state.query.toLowerCase(); const region=$('#region').value; return state.data.players.filter(p=>(!q||p.name.toLowerCase().includes(q))&&(region==='Alle'||p.region===region));}
function renderModes(){const ms=state.data.modes;$('#rankings').innerHTML=ms.map(m=>`<button class="mode ${m.id===state.mode?'active':''}" data-mode="${m.id}"><img src="/assets/icons/${esc(m.icon)}"><b>${esc(m.label)}</b><small>◉ Live: ${120+Math.floor(Math.random()*220)}</small></button>`).join('');document.querySelectorAll('.mode').forEach(x=>x.onclick=()=>{state.mode=x.dataset.mode;render();});}
function renderSideModes(){const ms=state.data.modes;$('#sideModes').innerHTML=ms.map(m=>`<button class="sideLink" data-mode="${m.id}"><img src="/assets/icons/${esc(m.icon)}" style="width:20px;height:20px;object-fit:contain"><span>${esc(m.label)}</span></button>`).join('');document.querySelectorAll('#sideModes .sideLink').forEach(x=>x.onclick=()=>{state.mode=x.dataset.mode;render();});}
function sorted(){return [...filteredPlayers()].sort((a,b)=>tierValue(a.tiers[state.mode])-tierValue(b.tiers[state.mode]));}
function renderTierlist(){const arr=sorted();const tiers=['HT5','HT4','HT3','HT2','HT1','LT1','LT2','LT3','LT4','LT5'];const rows=[];for(const t of tiers){const ps=arr.filter(p=>p.tiers[state.mode]===t);if(!ps.length)continue;rows.push(`<div class="tierRow"><div class="tierLabel ${tierClass(t)}">${t}</div>${[0,1,2,3,4].map(i=>{const p=ps[i];return p?`<div class="person" data-name="${esc(p.name)}"><img class="avatar" src="${skin(p.name)}"><div><b>${esc(p.name)}</b><small>${flag(p.region)} ${esc(p.region)} · ${esc(p.siteRank||'User')}</small></div></div>`:'<div></div>'}).join('')}<div class="arrow">›</div></div>`)}$('#tierRows').innerHTML=rows.join('')||'<div style="padding:30px;color:#718092">Keine Spieler für diese Auswahl.</div>';document.querySelectorAll('.person[data-name]').forEach(x=>x.onclick=()=>openProfile(x.dataset.name));}
function renderTop3(){const arr=sorted().slice(0,3);$('#top3').innerHTML=arr.map((p,i)=>`<div class="topPerson"><img class="avatar" src="${skin(p.name)}"><b>${esc(p.name)}</b><small>${esc(p.tiers[state.mode]||'—')}</small><div style="font-size:8px;color:#667586">${(12000-i*1700).toLocaleString('de-DE')} Punkte</div></div>`).join('');}
function renderChanges(){const arr=state.data.players.slice(0,5);$('#changes').innerHTML=arr.map((p,i)=>`<div class="changesRow"><div class="dot">♛</div><b>${esc(p.name)}</b><span>+1 Tier</span><small>vor ${5+i*7}m</small></div>`).join('');}
function renderRegions(){const c={};state.data.players.forEach(p=>c[p.region]=(c[p.region]||0)+1);$('#regions').innerHTML=Object.entries(c).sort((a,b)=>b[1]-a[1]).map(([r,n])=>`<div class="regionRow"><span>${flag(r)}</span><b>${r==='EU'?'Europa':r==='NA'?'USA':r}</b><span>${n}</span></div>`).join('');}
function openProfile(name){const p=state.data.players.find(x=>x.name===name);if(!p)return;$('#modalCard').innerHTML=`<button class="closeModal" onclick="closeModal()">×</button><div class="profileHead"><img src="${skin(p.name)}"><div><h2>${esc(p.name)}</h2><p>${esc(p.rank||'Combat Player')} · ${flag(p.region)} ${esc(p.region)} · ${esc(p.siteRank||'User')}</p></div></div><div class="profileTiers">${state.data.modes.map(m=>`<div class="profileTier"><b>${esc(m.label)}</b><span class="${tierClass(p.tiers[m.id])}">${esc(p.tiers[m.id]||'Unranked')}</span></div>`).join('')}</div>`;$('#modal').classList.add('open');}
function closeModal(){$('#modal').classList.remove('open');}
function openAdmin(){ $('#modalCard').innerHTML=`<button class="closeModal" onclick="closeModal()">×</button><h2>Admin Panel</h2><p style="color:#8390a0">Spieler hinzufügen, Tiers ändern und Website-Ränge verwalten.</p><div class="adminGrid"><label>Spielername<input id="aName" placeholder="PlayerName"></label><label>Region<select id="aRegion"><option>EU</option><option>NA</option><option>AS</option><option>OC</option></select></label><label>Website-Rang<select id="aRank"><option>User</option><option>Tester</option><option>Media</option><option>Helper</option><option>Moderator</option><option>Admin</option><option>Owner</option></select></label><label>UHC Tier<select id="aTier"><option>HT1</option><option>HT2</option><option>HT3</option><option>HT4</option><option>HT5</option><option>LT1</option><option>LT2</option><option>LT3</option><option>LT4</option><option>LT5</option></select></label></div><div class="adminActions"><button class="primary" id="addPlayer">Spieler hinzufügen</button></div><div class="adminList"><h3>Vorhandene Spieler</h3>${state.data.players.map(p=>`<div class="rankRow"><span>${esc(p.name)} · ${esc(p.region)}</span><span class="badge">${esc(p.siteRank||'User')}</span></div>`).join('')}</div>`;$('#modal').classList.add('open');$('#addPlayer').onclick=addPlayer;}
async function addPlayer(){const name=$('#aName').value.trim();if(!name)return toast('Spielername fehlt.');const tiers={};state.data.modes.forEach(m=>tiers[m.id]=$('#aTier').value);const body={name,region:$('#aRegion').value,rank:'Combat Player',siteRank:$('#aRank').value,tiers};const r=await fetch('/api/admin/players',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){const e=await r.json().catch(()=>({}));return toast(e.error||'Admin-Login erforderlich.')}state.data=await fetch('/api/data').then(x=>x.json());closeModal();render();toast('Spieler hinzugefügt');}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
$('#search').oninput=e=>{state.query=e.target.value;$('#sideSearch').value=e.target.value;renderTierlist();renderTop3()};$('#sideSearch').oninput=e=>{state.query=e.target.value;$('#search').value=e.target.value;renderTierlist();renderTop3()};$('#region').onchange=()=>{renderTierlist();renderTop3()};$('#copyIp').onclick=()=>navigator.clipboard?.writeText($('#serverIp').textContent).then(()=>toast('Server-IP kopiert'));$('#adminBtn').onclick=openAdmin;$('#ranksBtn').onclick=openAdmin;$('#drawerAdmin').onclick=openAdmin;$('#drawerRanks').onclick=openAdmin;$('#menuBtn').onclick=()=>{$('#drawer').classList.add('open');$('#backdrop').classList.add('open')};$('#drawerClose').onclick=()=>{$('#drawer').classList.remove('open');$('#backdrop').classList.remove('open')};$('#backdrop').onclick=()=>{$('#drawer').classList.remove('open');$('#backdrop').classList.remove('open')};$('#themeBtn').onclick=()=>document.body.classList.toggle('light');$('#modal').onclick=e=>{if(e.target.classList.contains('modalBg'))closeModal()};document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search').focus()}if(e.key==='Escape'){closeModal();$('#drawer').classList.remove('open');$('#backdrop').classList.remove('open')}});load().catch(e=>{console.error(e);toast('Daten konnten nicht geladen werden')});
