const data=[
{name:"Marlowww",points:450,region:"NA",skin:"Marlowww",tiers:[["crystal","HT1"],["pearl","HT1"],["mace","HT1"],["armor","HT1"],["sword","HT1"],["pot","HT1"]]},
{name:"ItzReal",points:410,region:"NA",skin:"ItzReal",tiers:[["sword","HT1"],["crystal","HT1"],["pearl","HT1"],["mace","HT1"],["pot","HT1"],["armor","LT1"]]},
{name:"Romeo",points:390,region:"EU",skin:"Romeo",tiers:[["sword","HT2"],["crystal","HT2"],["mace","HT3"],["pearl","LT2"],["pot","HT3"],["armor","LT2"]]}
];
const labels={crystal:'Crystal',pearl:'Pearl',mace:'Mace',armor:'Armor',sword:'Sword',pot:'Pot'};
function icon(mode){return `<img src="assets/icons/${mode}.png" alt="${labels[mode]}" class="tierIcon">`}
function skin(name){return `<img src="https://mc-heads.net/avatar/${encodeURIComponent(name)}/128" alt="${name} Minecraft Skin" class="skinHead">`}
function render(){let q=(document.getElementById('search').value||'').toLowerCase();let arr=data.filter(p=>p.name.toLowerCase().includes(q));document.getElementById('players').innerHTML=arr.map((p,i)=>`<article class="player" tabindex="0" role="button" onclick="openProfile(${data.indexOf(p)})" onkeydown="if(event.key==='Enter'||event.key===' ')openProfile(${data.indexOf(p)})"><div class="playerTop"><div class="place"><b>${i+1}.</b>${skin(p.skin)}</div><div><div class="name">${p.name}</div><div class="region">🏅 Combat Grandmaster (${p.points} points)</div><div class="clickHint">Profil ansehen →</div></div><div class="rankNA">${p.region}</div></div><div class="tiersTitle">TIERS</div><div class="tiers">${p.tiers.map(t=>`<div class="tierItem"><div class="icon">${icon(t[0])}</div><span class="tier ${t[1].startsWith('LT')?'lt':''}">${t[1]}</span></div>`).join('')}</div></article>`).join('')||'<div class="player"><h2>Kein Spieler gefunden</h2></div>'}
function filterPlayers(){render()}
function setCategory(c){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));event.currentTarget.classList.add('active')}
render();

function openProfile(index){const p=data[index];if(!p)return;const best=p.tiers.filter(t=>t[1].startsWith('HT')).length;document.getElementById('profileContent').innerHTML=`<div class="profileHero"><div class="profileSkin">${skin(p.skin)}</div><div class="profileIdentity"><div class="profileEyebrow">PLAYER PROFILE</div><h1 id="profileName">${p.name}</h1><p>Combat Grandmaster · ${p.points} points</p></div><div class="profileRegion">${p.region}</div></div><div class="profileStats"><div><span>Points</span><b>${p.points}</b></div><div><span>HT Tiers</span><b>${best}</b></div><div><span>Tests</span><b>${p.tiers.length}</b></div></div><div class="profileSectionTitle">ALL TIERS</div><div class="profileTiers">${p.tiers.map(t=>`<div class="profileTier"><div class="profileTierIcon">${icon(t[0])}</div><div><b>${labels[t[0]]}</b><span class="tier ${t[1].startsWith('LT')?'lt':''}">${t[1]}</span></div></div>`).join('')}</div><div class="profileFooter"><span>Stabletiers profile</span><span>Updated live</span></div>`;document.getElementById('profileModal').classList.add('open');document.getElementById('profileModal').setAttribute('aria-hidden','false');document.body.classList.add('modalOpen')}
function closeProfile(){document.getElementById('profileModal').classList.remove('open');document.getElementById('profileModal').setAttribute('aria-hidden','true');document.body.classList.remove('modalOpen')}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeProfile()});